name: 🐞 Vulnerable JuiceShop Workflow.
on:
  push:
    branches:
      - main
    paths:
      - apps/juice-shop/**
  pull_request:
    branches: 
      - main
    paths:
      - apps/juice-shop/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: JuiceShop - Trivy | Container Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/bkimminich/juice-shop:latest:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

