name: 🐞 Vulnerable JuiceShop Workflow.
on:
  push:
    branches:
      - main
    paths:
      - apps/juice-shop/**
  pull_request:
    branches: 
      - main
    paths:
      - apps/juice-shop/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: JuiceShop - Build image
      run: |
        sudo apt update ; sudo apt install net-tools -y
        ping -c 4 localhost
        docker pull bkimminich/juice-shop:latest
        docker run -d --rm -p 3000:3000 bkimminich/juice-shop:latest --name juiceshop

    - name: JuiceShop - Trivy | Container Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/bkimminich/juice-shop:latest'
        format: 'table'
        exit-code: '0'
        #exit-code: '1' # Quebrar build caso sejam encontradas vulnerabilidades com as severidades descritas
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: JuiceShop - Dastardly | Web Application Scanning
      # run: |
      #   docker run -d --rm -p 3000:3000 bkimminich/juice-shop:latest
      uses: PortSwigger/dastardly-github-action@main
      #continue-on-error: true 
      continue-on-error: false #Quebra esteira
      with:
        target-url: 'http://juiceshop:3000'

    - name: JuiceShop - Dastardly | Publish Test Report
      if: always() # Forces this step to always run
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/dastardly-report.xml' # You need to update this path if you pass in a different output filename to the Dastardly action
        require_tests: true

