name: 🐞 Vulnerable JuiceShop Workflow.
on:
  push:
    branches:
      - main
    paths:
      - apps/juice-shop/**
  pull_request:
    branches: 
      - main
    paths:
      - apps/juice-shop/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: JuiceShop - Build image 
      run: |
        docker pull docker.io/bkimminich/juice-shop
        #docker run --rm -p 80:3000 bkimminich/juice-shop:${{ github.sha }} .

    - name: JuiceShop - Trivy | Container Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/bkimminich/juice-shop:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

